Issue 278: Fix segment number
pravega/pravega-client-rust pull request #279
Opened 2021-06-18 01:49 UTC by Tristan1900

**Change log description**  
Fix segment number not starting from 0 issue.

**Purpose of the change**  
FIx #278

**What the code does**  
When user passes a segment with number x , byte writer first fetches the current list of segment of this stream from server. Then it sorts the list of segment by their segment number and gets the segment of index x. 

**How to verify it**  
Tests should pass.

2021-06-25 01:07 UTC, tkaitchuck requested changes
I don't think we want to adjust the number given to us by users. We should instead just take the stream name and work it out from the controller.

2021-07-07 10:57 UTC, shrids approved these changes
LGTM apart from the two errors in the tests.

2021-07-08 01:09 UTC, tkaitchuck reviewed
This looks good. But it's changing a public API so you'll need to bump the version number in the toml.

2021-07-08 01:09 UTC, tkaitchuck commented on integration_test/src/lib.rs
> +        // info!("Running integration test");
What's going on here?

2021-07-14 00:12 UTC, Tristan1900 commented on integration_test/src/lib.rs
> +        // info!("Running integration test");
fixed!

2021-07-14 19:10 UTC, tkaitchuck approved these changes

2021-07-14 19:10 UTC, merged