Fix transaction id format error
pravega/pravega-client-rust pull request #290
Opened 2021-07-08 23:11 UTC by Tristan1900

**Change log description**  
The hexadecimal based transaction id was using upper case letter whereas lower case letter should be used.

**What the code does**  
use lower case letter

**How to verify it**  
test should pass

2021-07-09 06:19 UTC, shrids requested changes

2021-07-09 06:19 UTC, shrids commented on integration_test/src/transactional_event_writer_tests.rs
> +async fn test_multiple_transactions(factory: &ClientFactory, stream: ScopedStream) {
Is this test being invoked?

2021-07-13 02:25 UTC, Tristan1900 commented on integration_test/src/transactional_event_writer_tests.rs
> +async fn test_multiple_transactions(factory: &ClientFactory, stream: ScopedStream) {
fixed, thanks!

2021-07-13 04:03 UTC, shrids approved these changes

2021-07-13 18:35 UTC, tkaitchuck approved these changes

2021-07-13 18:35 UTC, merged